import type { Metadata } from "next";
import { ArrowRight, CalendarDays, Check, Database, Link2, PhoneCall, Route, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { SiteShell } from "@/components/site/site-chrome";

export const metadata: Metadata = { title: "Connected operations", description: "Send Ring On Demand calls, leads, and appointments to the phone, CRM, calendar, or workflow your team uses." };
const connectionTypes = [[PhoneCall,"Phone delivery","Use the approved destination and schedule for inbound call delivery."],[Database,"CRM delivery","Keep the campaign ID attached to the downstream record."],[CalendarDays,"Calendar booking","Pass campaign details into scheduling instead of asking twice."]];
export default function ConnectedAppsPage() {
  return <SiteShell><main className="connected-page"><section className="connected-hero"><div className="connected-line" aria-hidden="true"/><div><p className="section-code">Ring On Demand / Connected operations</p><h1>Send each delivery where your team already works.</h1><p>Send calls to your agents, leads to your selected system, and appointments to your calendar without entering the campaign details again.</p><div><Link className="button button-dark" href="/build-campaign?intent=demo">Map my workflow<ArrowRight aria-hidden="true" size={16}/></Link><Link className="text-link" href="/partners">Explore partners<ArrowRight aria-hidden="true" size={15}/></Link></div></div></section><section className="connected-foundation"><div className="section-heading"><p className="section-code">[01] One set of campaign details</p><div><h2>Keep your campaign details attached to every delivery.</h2><p>Your locations, hours, volume, customer criteria, and destination stay with the campaign after review.</p></div></div><div className="connected-feature-grid">{connectionTypes.map(([Icon,title,copy],index)=>{const I=Icon as typeof Link2;return <article key={String(title)}><span>0{index+1}</span><I aria-hidden="true"/><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div></section><section className="connected-control"><div><p className="section-code">[02] Buyer control</p><h2>Check the details before they move.</h2><p>Your campaign details do not move until you review the answers and choose the destination.</p></div><div>{["Reviewed campaign details","Selected destination","Duplicate-safe delivery","Visible delivery status"].map(item=><p key={item}><Check aria-hidden="true"/>{item}</p>)}</div></section><section className="connected-flow"><p className="section-code">[03] How delivery works</p><div>{[[ShieldCheck,"Review"],[Route,"Deliver"],[Link2,"Confirm"]].map(([Icon,label],index)=>{const I=Icon as typeof Route;return <article key={String(label)}><span>{index+1}</span><I aria-hidden="true"/><h3>{String(label)}</h3></article>})}</div></section></main></SiteShell>;
}
