import type { Metadata } from "next";
import { ArrowRight, CalendarDays, Check, Database, Link2, PhoneCall, Route, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { SiteShell } from "@/components/site/site-chrome";

export const metadata: Metadata = { title: "Connected operations", description: "Carry approved Ring On Demand campaign data into phone, CRM, calendar, and operational workflows." };
const connectionTypes = [[PhoneCall,"Phone routing","Use the approved destination and schedule for inbound call delivery."],[Database,"CRM handoff","Keep the campaign identifier attached to the downstream record."],[CalendarDays,"Calendar handoff","Pass campaign context into scheduling instead of asking twice."]];
export default function ConnectedAppsPage() {
  return <SiteShell><main className="connected-page"><section className="connected-hero"><div className="connected-line" aria-hidden="true"/><div><p className="section-code">Ring On Demand / Connected operations</p><h1>Connect campaign intent to the systems that act on it.</h1><p>Move an approved campaign into routing, scheduling, and operational handoff without rebuilding the buy box in every tool.</p><div><Link className="button button-dark" href="/build-campaign?intent=demo">Map my workflow<ArrowRight aria-hidden="true" size={16}/></Link><Link className="text-link" href="/partners">Explore partners<ArrowRight aria-hidden="true" size={15}/></Link></div></div></section><section className="connected-foundation"><div className="section-heading"><p className="section-code">[01] One canonical record</p><div><h2>Connect without losing the campaign rules.</h2><p>Only named integrations approved in the proof register are published. The connection model works before a vendor is selected.</p></div></div><div className="connected-feature-grid">{connectionTypes.map(([Icon,title,copy],index)=>{const I=Icon as typeof Link2;return <article key={String(title)}><span>0{index+1}</span><I aria-hidden="true"/><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div></section><section className="connected-control"><div><p className="section-code">[02] Controlled access</p><h2>Keep approval in the loop.</h2><p>Campaign data does not move until the buyer approves the structured record and destination.</p></div><div>{["Approved campaign version","Explicit destination","Idempotent handoff","Delivery state and retry record"].map(item=><p key={item}><Check aria-hidden="true"/>{item}</p>)}</div></section><section className="connected-flow"><p className="section-code">[03] Operational sequence</p><div>{[[ShieldCheck,"Approve"],[Route,"Deliver"],[Link2,"Confirm"]].map(([Icon,label],index)=>{const I=Icon as typeof Route;return <article key={String(label)}><span>{index+1}</span><I aria-hidden="true"/><h3>{String(label)}</h3></article>})}</div></section></main></SiteShell>;
}
