import type { Metadata } from "next";
import { ArrowRight, CalendarDays, Check, Database, Link2, PhoneCall, Route, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { SiteShell } from "@/components/site/site-chrome";

export const metadata: Metadata = { title: "Connected operations", description: "Send Ring On Demand calls, leads, and appointments to the phone, CRM, calendar, or workflow your team uses." };
const connectionTypes = [[PhoneCall,"Phone routing","Use the approved destination and schedule for inbound call delivery."],[Database,"CRM handoff","Keep the campaign identifier attached to the downstream record."],[CalendarDays,"Calendar handoff","Pass campaign context into scheduling instead of asking twice."]];
export default function ConnectedAppsPage() {
  return <SiteShell><main className="connected-page"><section className="connected-hero"><div className="connected-line" aria-hidden="true"/><div><p className="section-code">Ring On Demand / Connected operations</p><h1>Send demand where your team already works.</h1><p>Route calls to your agents, deliver leads to your selected system, and pass appointments to your calendar without entering the campaign details again.</p><div><Link className="button button-dark" href="/build-campaign?intent=demo">Map my workflow<ArrowRight aria-hidden="true" size={16}/></Link><Link className="text-link" href="/partners">Explore partners<ArrowRight aria-hidden="true" size={15}/></Link></div></div></section><section className="connected-foundation"><div className="section-heading"><p className="section-code">[01] One campaign record</p><div><h2>Keep the buy box attached to every delivery.</h2><p>Your locations, hours, volume, qualification rules, and destination stay with the campaign from approval through handoff.</p></div></div><div className="connected-feature-grid">{connectionTypes.map(([Icon,title,copy],index)=>{const I=Icon as typeof Link2;return <article key={String(title)}><span>0{index+1}</span><I aria-hidden="true"/><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div></section><section className="connected-control"><div><p className="section-code">[02] Buyer control</p><h2>Approve the details before they move.</h2><p>Campaign data does not move until you approve the structured record and choose the destination.</p></div><div>{["Approved campaign version","Selected destination","Duplicate-safe handoff","Visible delivery status"].map(item=><p key={item}><Check aria-hidden="true"/>{item}</p>)}</div></section><section className="connected-flow"><p className="section-code">[03] How the handoff works</p><div>{[[ShieldCheck,"Approve"],[Route,"Deliver"],[Link2,"Confirm"]].map(([Icon,label],index)=>{const I=Icon as typeof Route;return <article key={String(label)}><span>{index+1}</span><I aria-hidden="true"/><h3>{String(label)}</h3></article>})}</div></section></main></SiteShell>;
}
